from src.summary_agent import SummaryAgent
from src.medicine_agent import MedicineManagementAgent
from src.stock_agent import StockManagementAgent
from src.registration_agent import RegistrationAgent
from src.patient_agent import PatientManagementAgent
from src.navigation_agent import PatientNavigationAgent
from src.telemetry_agent import TelemetryAgent
from src.band_config import HealthcareOrchestrationRoom, ReceptionNavigationRoom, ClinicalConsultRoom, PharmacyInventoryRoom, TelemetryAuditRoom

